config/routes.rb
Rails.application.routes.draw do
  get 'pages/lazy_load', to: "pages#lazy_load"
  resources :posts
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def lazy_load
    # sleep(2)
    # @posts = Post.all
    @posts = Post.limit(100)
    render partial: "posts/posts", posts: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LazyLoadDeaninVideo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_post_template.html.erb
<div class="animate-pulse p-6 flex flex-col h-64">
  <div class="flex-1 bg-gray-400 rounded-lg shadow-md p-4 md-4 flex flex-col justify-between">
    <div>
      <div class="font-bold text-x1 mb-2 h-4 bg-gray-400 rounded w-full">
        <div class="text-base space-y-4">
          <div class="h-4 bg-gray-400 rounded w-full"></div>
          <div class="h-4 bg-gray-400 rounded w-full"></div>
          <div class="h-4 bg-gray-400 rounded w-full"></div>
          <div class="h-4 bg-gray-400 rounded w-full"></div>
        </div>
      </div>
    </div>
    <div class="mt-2 h-4 bg-gray-400 rounded w-64"></div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class='flex flex-col items-center justify-center'
    data-controller='content-loader'
    data-content-loader-url-value="<%= pages_lazy_load_path %>" >
  <div class="flex items-center mb-4">
    <i class="fas fa-spinner fa-spin text-4x1 mr-2"></i>
  </div>
  <span>Loading Posts...</span>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <%=10.times do %>
      <div class="p-4 h-full">
        <%=render "post_template"%>
      </div>
    <%end%>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="p-6 flex flex-col h-full">
  <div class="flex-1 bg-white rounded-lg shadow-md p-4 mb-4 flex flex-col justify-between">
    <div>
      <p class="font-bold text-x1 mb-2">
        <%= post.title%>
      </p>
      <p class="text-gray-700 text-base">
        <%= post.body%>
      </p>
    </div>
    <% if local_assigns[:show_link] %>
      <div class="mt-2">
        <%= link_to "Show this post", post, class: "text-blue-500 hover:text-blue-800" %>
      </div>
    <%end%>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid:cols-3 gap-4">
  <% @posts.each do |post| %>
    <div class="p-4 h-full">
      <%= render post, show_link: true%>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Posts</h1>
<div id="posts">
  <%= render @posts %>
</div>
<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>